# Generated by Django 5.2.8 on 2026-01-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='archived_tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water Bill'), ('electricity', 'Electricity Bill'), ('garbage', 'Garbage Fee'), ('damage', 'Damage Repair'), ('deposit', 'Security Deposit'), ('penalty', 'Late Payment Penalty'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
