# Generated by Django 5.2.8 on 2025-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water Bill'), ('electricity', 'Electricity Bill'), ('garbage', 'Garbage Fee'), ('damage', 'Damage Repair'), ('deposit', 'Security Deposit'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
