# Generated by Django 5.2.8 on 2026-02-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_payment_rejection_reason_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, error_messages={'unique': 'This transaction code has already been used.'}, max_length=50, unique=True),
        ),
    ]
