# Generated by Django 5.2.8 on 2025-12-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
