# Generated by Django 5.2.8 on 2026-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_bill_amount_paid_contract_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
