# Generated by Django 5.2.8 on 2026-04-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_contract_date_accepted_contract_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_has_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
