# Generated by Django 5.2.8 on 2025-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_bill_tenant_alter_contract_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='archived_tenant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived_tenant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_tenant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
