# Generated by Django 5.2.8 on 2025-12-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_bill_archived_tenant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archived_house_number',
            field=models.CharField(blank=True, help_text='Preserves house number if house is deleted', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='estates.house'),
        ),
    ]
