# Generated by Django 5.2.8 on 2026-01-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='archived_reported_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
