# Generated by Django 5.2.8 on 2026-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest_archived_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='archived_house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
