# Generated by Django 5.2.8 on 2025-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancerequest_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='archived_reported_by',
            field=models.CharField(blank=True, help_text='Preserves user name if user is deleted', max_length=150),
        ),
    ]
