# Generated by Django 5.2.8 on 2025-12-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_contract_archived_house_number_alter_contract_house'),
        ('maintenance', '0005_maintenancerequest_archived_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='archived_house_number',
            field=models.CharField(blank=True, help_text='Preserves house number if house is deleted', max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='estates.house'),
        ),
    ]
