# Generated by Django 4.2.7 on 2025-12-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('structural', 'Structural'), ('pest_control', 'Pest Control'), ('general', 'General Maintenance')], max_length=50, null=True),
        ),
    ]
